{
 "title": "Statisfactory",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Depots Over Time",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 10, "x": 0, "y": 0 },
   "targets": [
    { "expr": "depot", "legendFormat": "{{item}}" }
   ]
  },
  {
   "title": "Dimensional Depots",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 7, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sort_desc(depot)", "legendFormat": "{{item}}" }
   ]
  },
  {
   "title": "AWESOME Points",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "expr": "(-1 * idelta(points_to_next_coupon[10s])) * 12",
     "legendFormat": "Points Per Minute"
    },
    { "expr": "points_to_next_coupon", "legendFormat": "Points Until Next Coupon" }
   ]
  },
  {
   "title": "FICSIT Coupons",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "coupons + ignoring(item) depot{item=\"FICSIT Coupon\"}",
     "legendFormat": "Total"
    },
    { "expr": "coupons", "legendFormat": "Pending" }
   ]
  },
  {
   "title": "Power Consumption",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
   "targets": [
    { "expr": "power_produced", "legendFormat": "Power Produced" },
    { "expr": "power_consumed", "legendFormat": "Power Consumed" },
    { "expr": "maximum_power_consumption", "legendFormat": "Max Consumption" },
    { "expr": "power_production_capacity", "legendFormat": "Power Capacity" }
   ]
  }
 ]
}